In [1]:
import pandas as pd

In [21]:
df = pd.read_csv("analysis_id(in).csv")

In [22]:
#head of the dataframe
df.head()

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [23]:
df.isna().sum()

Unnamed: 0                   0
date_hour                    0
client                       0
device_type                  0
time_zone                    0
os_name                      0
browser_name                 0
ad_unit                      0
size                         0
bidder                       0
bid_range                    0
media_type                   0
request_count                0
response_count               0
prebid_win_count          3833
win_count                 4814
sum_bid                   1210
sum_time_to_respond       1210
median                    3240
min_bid                   1210
max_bid                   1210
avg_bid                   1210
sum_2nd_highest_bid       4266
sum_prebid_winning_bid    3833
sum_winning_bid           4814
sum_nobid                 5000
sum_timeout               5000
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              5000 non-null   int64
 1   date_hour               5000 non-null   object
 2   client                  5000 non-null   object
 3   device_type             5000 non-null   object
 4   time_zone               5000 non-null   object
 5   os_name                 5000 non-null   object
 6   browser_name            5000 non-null   object
 7   ad_unit                 5000 non-null   object
 8   size                    5000 non-null   object
 9   bidder                  5000 non-null   object
 10  bid_range               5000 non-null   object
 11  media_type              5000 non-null   object
 12  request_count           5000 non-null   int64
 13  response_count          5000 non-null   int64
 14  prebid_win_count        1167 non-null   float64
 15  win_count               186 non-null    float64
 16  sum_bid                 3790 non-null   float64
 17  sum_time_to_respond     3790 non-null   float64
 18  median                  1760 non-null   float64
 19  min_bid                 3790 non-null   float64
 20  max_bid                 3790 non-null   float64
 21  avg_bid                 3790 non-null   float64
 22  sum_2nd_highest_bid     734 non-null    float64
 23  sum_prebid_winning_bid  1167 non-null   float64
 24  sum_winning_bid         186 non-null    float64
 25  sum_nobid               0 non-null      float64
 26  sum_timeout             0 non-null      float64
dtypes: float64(13), int64(3), object(11)
memory usage: 1.0+ MB

In [25]:
df['bidder'].unique()

array(['onemobile', 'rhythmone', 'undertone', ' ', 'pulsepoint',
       'pubmatic', 'triplelift', 'sharethrough', 'ix', 'medianet',
       'appnexus', '33across', 'openx', 'emx_digital', 'rubicon',
       'criteo', 'sovrn', 'teads'], dtype=object)

In [26]:
df = df.drop(columns=["Unnamed: 0"])

In [28]:
# removing the values of bidder " "
df_new = df[df['bidder'] != " "].reset_index(drop=True)

In [40]:
# filling the prebid win count with zero
df_new['prebid_win_count'] = df_new['prebid_win_count'].fillna(0)
df_new['win_count'] = df_new['win_count'].fillna(0)

In [41]:
df_new['bidder'].unique()

array(['onemobile', 'rhythmone', 'undertone', 'pulsepoint', 'pubmatic',
       'triplelift', 'sharethrough', 'ix', 'medianet', 'appnexus',
       '33across', 'openx', 'emx_digital', 'rubicon', 'criteo', 'sovrn',
       'teads'], dtype=object)

In [42]:
data =  df_new[["bidder", "request_count", "response_count","prebid_win_count","win_count"]]

In [43]:
data.isna().sum()

bidder              0
request_count       0
response_count      0
prebid_win_count    0
win_count           0
dtype: int64

In [63]:
final_df = data.groupby("bidder").agg({"request_count":"sum" ,
                            "prebid_win_count" :"sum",
                            "response_count":"sum",
                            "prebid_win_count":"sum",
                            "win_count":"sum"}).reset_index()

In [64]:
final_df

          bidder  request_count  prebid_win_count  response_count  win_count
0       33across            886             136.0             886       19.0
1       appnexus            830             175.0             830       10.0
2         criteo           3181             587.0            3181       21.0
3    emx_digital            393              56.0             393       20.0
4             ix           3051             184.0            3051       13.0
5       medianet           2556             253.0            2556       20.0
6      onemobile           2726             759.0            2726       35.0
7          openx           1165              86.0            1165        7.0
8       pubmatic           2335             255.0            2335       57.0
9     pulsepoint            191              71.0             191        5.0
10     rhythmone            655             160.0             655       18.0
11       rubicon            582              33.0             582        0.0
12  sharethrough            332             104.0             332       10.0
13         sovrn            358              14.0             358        1.0
14         teads            700             323.0             700       16.0
15    triplelift           1479             108.0            1479       10.0
16     undertone            104              52.0             104       16.0

In [65]:
# calculating the win rate in final_Df
final_df['win_rate'] = final_df['win_count']*100/ final_df['request_count']
final_df['win_rate'] = final_df['win_rate'].round(2)

final_df['prebid_win_rate'] = final_df['prebid_win_count']*100/ final_df['request_count']
final_df['prebid_win_rate'] = final_df['prebid_win_rate'].round(2)

In [67]:
final_df.sort_values(by=["win_rate","prebid_win_rate"], ascending=[False,False]).reset_index(drop=True)

,bidder,request_count,prebid_win_count,response_count,win_count,win_rate,prebid_win_rate
0,undertone,104,52.0,104,16.0,15.38,50.00
1,emx_digital,393,56.0,393,20.0,5.09,14.25
2,sharethrough,332,104.0,332,10.0,3.01,31.33
3,rhythmone,655,160.0,655,18.0,2.75,24.43
4,pulsepoint,191,71.0,191,5.0,2.62,37.17
5,pubmatic,2335,255.0,2335,57.0,2.44,10.92
6,teads,700,323.0,700,16.0,2.29,46.14
7,33across,886,136.0,886,19.0,2.14,15.35
8,onemobile,2726,759.0,2726,35.0,1.28,27.84
9,appnexus,830,175.0,830,10.0,1.20,21.08
10,medianet,2556,253.0,2556,20.0,0.78,9.90
11,triplelift,1479,108.0,1479,10.0,0.68,7.30
12,criteo,3181,587.0,3181,21.0,0.66,18.45
13,openx,1165,86.0,1165,7.0,0.60,7.38
14,ix,3051,184.0,3051,13.0,0.43,6.03
15,sovrn,358,14.0,358,1.0,0.28,3.91
16,rubicon,582,33.0,582,0.0,0.00,5.67

In [73]:
result_df  = final_df[['bidder','prebid_win_rate','win_rate']].sort_values(by="prebid_win_rate", ascending=False).reset_index(drop=True)
result_df.head(2)

      bidder  prebid_win_rate  win_rate
0  undertone            50.00     15.38
1      teads            46.14      2.29